server:
  port: 5555

spring:
  main:
    allow-circular-references: true
  profiles:
    active: developer
  web:
    locale: en
  datasource:
    url: jdbc:h2:./devdb;Auto_server=TRUE
    username: sa
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create

websiteconfiguration:
  email:
    username: kieran.herman15@ethereal.email
    password: ${PROJECT_EMAIL_PASSWORD}
    host: smtp.ethereal.email
    port: 587
    from: fahrettingursoy@yandex.com
  client:
    host: http://localhost:3434
---
spring:
  config:
    activate:
      on-profile: production
websiteconfiguration:
  client:
    host: http://www.fahrettingursoy.com
---
spring:
  config:
    activate:
      on-profile: developer
websiteconfiguration:
  client:
    host: http://localhost:3434


    # Console bölümünde hata mesajlarınu loglayarak gösterim sağlar
logging:
  level:
    ROOT: ERROR
#    DEBUG
#    ERROR
#    FATAL
#    INFO
#    OFF
#    TRACE
#    WARN