server:
  port: 5555


spring:
  main:
    allow-circular-references: true
  profiles:
    active: developer
  web:
    locale: en
  datasource:
    url: jdbc:postgresql://localhost:5432/brssistem
    username: postgres
    password: 123
    hikari: auto-commit
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update

websiteconfiguration:
  token-type: OpaqueTokenService
  email:
    username: kieran.herman15@ethereal.email
    password: ${PROJECT_EMAIL_PASSWORD}
    host: smtp.ethereal.email
    port: 587
    from: fahrettingursoy@yandex.com
  client:
    host: http://localhost:3434
---
spring:
  config:
    activate:
      on-profile: production
websiteconfiguration:
  client:
    host: http://www.fahrettingursoy.com

---
spring:
  config:
    activate:
      on-profile: developer
websiteconfiguration:
  client:
    host: http://localhost:3434

    # Console bölümünde hata mesajlarını loglayarak gösterim sağlar
#logging:
#  level:
#    ROOT: ERROR
#    DEBUG
#    ERROR
#    FATAL
#    INFO
#    OFF
#    TRACE
#    WARN